iChange = 1
bRemove = False
bPython = True
bHideInactive = True
Activities = ["AWAKE", "HOLD", "SLEEP", "HEAL", "SENTRY", "INTERCEPT", "MISSION", "PATROL", "PLUNDER"]
iSetValue = 3
iWarValue = 0
iChangeType = 2
iPlotType = 2
iOwnerType = 0
bApplyAll = False
iSelectedPlayer = 0
iSelectedCiv = -1
iSelectedClass = -1