# Fresol: only use the Civ4SDK location when it is actually there, so that build
# environments without it (AppVeyor installs the Visual C++ Toolkit 2003 in its
# default location) fall back to the defaults in the Makefile instead of failing.
!IF [IF NOT EXIST "C:\Program Files (x86)\Civ4SDK\Microsoft Visual C++ Toolkit 2003\bin\cl.exe" EXIT 1] != 0
!ELSE
TOOLKIT=C:\Program Files (x86)\Civ4SDK\Microsoft Visual C++ Toolkit 2003
PSDK=C:\Program Files (x86)\Civ4SDK\WindowsSDK
!ENDIF
CUSTOM_LDFLAGS = psapi.lib
