## Sid Meier's Civilization 4
## Copyright Firaxis Games 2005

# Enum for screens...

from CvPythonExtensions import CivilopediaPageTypes

DOMESTIC_ADVISOR = 0
REWARD_SCREEN = 1
DAWN_OF_MAN = 2
TECH_CHOOSER = 3
FOREIGN_ADVISOR = 4
FINANCE_ADVISOR = 5
WONDER_MOVIE_SCREEN = 6
RELIGION_SCREEN = 7
INTRO_MOVIE_SCREEN = 8
CIVICS_SCREEN = 9
DIPLOMACY_SCREEN = 10
OPTIONS_SCREEN = 11
TECH_SPLASH = 12
REPLAY_SCREEN = 13
MILITARY_ADVISOR = 14
VICTORY_SCREEN = 15
TOP_CIVS = 16
TUTORIAL_SCREEN = 17
INFO_SCREEN = 18
ERA_MOVIE_SCREEN = 19
ADVISOR_SCREEN = 20
HALL_OF_FAME = 21
DAN_QUAYLE_SCREEN = 22
WORLDBUILDER_SCREEN = 23
WORLDBUILDER_DIPLOMACY_SCREEN = 24
VICTORY_MOVIE_SCREEN = 25
UN_SCREEN = 26
ESPIONAGE_ADVISOR = 27
SPACE_SHIP_SCREEN = 28
CORPORATION_SCREEN = 29

## World Builder ##
WB_TRADE = 63
WB_INFO = 64
WB_CORPORATION = 65
WB_RELIGION = 66
WB_UNITLIST = 67
WB_PLOT = 68
WB_EVENT = 69
WB_BUILDING = 70
WB_CITYDATA = 71
WB_CITYEDIT = 72
WB_TECH = 73
WB_PROJECT = 74
WB_TEAM = 75
WB_PLAYER = 76
WB_UNIT = 77
WB_PROMOTION = 78
WB_DIPLOMACY = 79
WB_GAMEDATA = 80
WB_STOREDDATA = 81
WB_PLAYER_ENABLED = 82

MAIN_INTERFACE = 99
DEBUG_INFO_SCREEN = 100

# Civilopedia Pages start at 200
# Civilopedia
PEDIA_MAIN			= 200
PEDIA_CIVS			= 201
PEDIA_LEADERS			= 202
PEDIA_CIVICS			= 203
PEDIA_RELIGIONS			= 204
PEDIA_CORPORATIONS		= 205
PEDIA_SPECIALISTS		= 206
PEDIA_TECHS			= 207
PEDIA_CULTURE_LEVELS		= 208
PEDIA_UNITS			= 209
PEDIA_MILITARY_UNITS		= 210
PEDIA_UNIQUE_UNITS		= 211
PEDIA_UNIT_CATEGORIES		= 212
PEDIA_UNIT_UPGRADES		= 213
PEDIA_PROMOTIONS		= 214
PEDIA_PROMOTION_TREE		= 215
PEDIA_BUILDINGS			= 216
PEDIA_RELIGIOUS_BUILDINGS	= 217
PEDIA_UNIQUE_BUILDINGS		= 218
PEDIA_NATIONAL_WONDERS		= 219
PEDIA_GREAT_WONDERS		= 220
PEDIA_PROJECTS			= 221
PEDIA_TERRAINS			= 222
PEDIA_FEATURES			= 223
PEDIA_RESOURCES			= 224
PEDIA_IMPROVEMENTS		= 225
PEDIA_ROUTES			= 226
PEDIA_CONCEPTS			= 227
PEDIA_HINTS			= 228
PEDIA_SHORTCUTS 		= 229
PEDIA_BTS_CONCEPTS		= 230
