## Sid Meier's Civilization 4
## Copyright Firaxis Games 2005

# Enum for screens...

from CvPythonExtensions import CivilopediaPageTypes

DOMESTIC_ADVISOR = 0
REWARD_SCREEN = 1
DAWN_OF_MAN = 2
TECH_CHOOSER = 3
FOREIGN_ADVISOR = 4
FINANCE_ADVISOR = 5
WONDER_MOVIE_SCREEN = 6
RELIGION_SCREEN = 7
INTRO_MOVIE_SCREEN = 8
CIVICS_SCREEN = 9
DIPLOMACY_SCREEN = 10
OPTIONS_SCREEN = 11
TECH_SPLASH = 12
REPLAY_SCREEN = 13
MILITARY_ADVISOR = 14
VICTORY_SCREEN = 15
TOP_CIVS = 16
TUTORIAL_SCREEN = 17
INFO_SCREEN = 18
ERA_MOVIE_SCREEN = 19
ADVISOR_SCREEN = 20
HALL_OF_FAME = 21
DAN_QUAYLE_SCREEN = 22
WORLDBUILDER_SCREEN = 23
WORLDBUILDER_DIPLOMACY_SCREEN = 24
VICTORY_MOVIE_SCREEN = 25
UN_SCREEN = 26
ESPIONAGE_ADVISOR = 27
SPACE_SHIP_SCREEN = 28
CORPORATION_SCREEN = 29

## World Builder ##
WB_TRADE = 63
WB_INFO = 64
WB_CORPORATION = 65
WB_RELIGION = 66
WB_UNITLIST = 67
WB_PLOT = 68
WB_EVENT = 69
WB_BUILDING = 70
WB_CITYDATA = 71
WB_CITYEDIT = 72
WB_TECH = 73
WB_PROJECT = 74
WB_TEAM = 75
WB_PLAYER = 76
WB_UNIT = 77
WB_PROMOTION = 78
WB_DIPLOMACY = 79
WB_GAMEDATA = 80
WB_STOREDDATA = 81

MAIN_INTERFACE = 99
DEBUG_INFO_SCREEN = 100

# Civilopedia Pages start at 200
# Civilopedia
PEDIA_PAGES_START = 200
PEDIA_NUM_PAGES = 32

(
	PEDIA_MAIN,
	PEDIA_CIVS,
	PEDIA_LEADERS,	
	PEDIA_CIVICS,
	PEDIA_RELIGIONS,
	PEDIA_CORPORATIONS,
	PEDIA_SPECIALISTS,
	PEDIA_TECHS,
	PEDIA_CULTURE_LEVELS,
	PEDIA_UNITS,
	PEDIA_MILITARY_UNITS,
	PEDIA_UNIQUE_UNITS,
	PEDIA_UNIT_CATEGORIES,
	PEDIA_UNIT_UPGRADES,
	PEDIA_PROMOTIONS,
	PEDIA_PROMOTION_TREE,
	PEDIA_BUILDINGS,
	PEDIA_RELIGIOUS_BUILDINGS,
	PEDIA_UNIQUE_BUILDINGS,
	PEDIA_GREAT_PEOPLE_BUILDINGS,
	PEDIA_NATIONAL_WONDERS,
	PEDIA_GREAT_WONDERS,
	PEDIA_PROJECTS,
	PEDIA_TERRAINS,
	PEDIA_FEATURES,
	PEDIA_RESOURCES,
	PEDIA_IMPROVEMENTS,
	PEDIA_ROUTES,
	PEDIA_CONCEPTS,
	PEDIA_HINTS,
	PEDIA_SHORTCUTS,
	PEDIA_BTS_CONCEPTS,
) = range(PEDIA_PAGES_START, PEDIA_PAGES_START + PEDIA_NUM_PAGES)
